#' getsitedc
#'
#' This function takes a RefCDS object and a bigwig file with duplex coverage as input and adds to the RefCDS two fields required to use site-level duplex coverage in dndscv. Usage: RefCDS = getsitedc(RefCDS)
#'
#' @author Inigo Martincorena (Wellcome Sanger Institute)
#' @details Martincorena I, et al. (2017) Universal patterns of selection in cancer and somatic tissues. Cell. 171(5):1029-1041.
#'
#' @param refcds Input refcds object
#' @param gr_genes Input gr_genes object available from the precomputed RefCDS files or generated by buildref
#' @param coverage_file Path to a bigwig file with the aggregate duplex coverage per site for all samples used to call mutations in the dataset
#'
#' @export

getsitedc = function(refcds, gr_genes, coverage_file) {
  
  ## For each gene in the RefCDS, we obtain the duplex depth per site and save the coverage vectors and position vectors in the RefCDS
  message("    Adding site-level duplex coverage to RefCDS...")
  
  # Querying the bigwig file for all positions in the refcds
  gene_list = sapply(refcds, function(x) x$gene_name)
  gr_all = gr_genes[gr_genes$names %in% gene_list]
  rle_cov = rtracklayer::import.bw(coverage_file, which = gr_all, as = "RleList") # Rle object with the coverage per site
  
  for (j in 1:length(refcds)) {
    
    # Exonic positions
    refcds[[j]]$intervals_cdsvec = as.integer(unlist(apply(refcds[[j]]$intervals_cds, 1, function(x) seq(x[1],x[2])))) # vector of chromosome coordinates
    refcds[[j]]$dcvec_cds = as.integer(rle_cov[[refcds[[j]]$chr]][refcds[[j]]$intervals_cdsvec])
    
    if (refcds[[j]]$strand==-1) { 
      refcds[[j]]$dcvec_cds = rev(refcds[[j]]$dcvec_cds)
      refcds[[j]]$intervals_cdsvec = rev(refcds[[j]]$intervals_cdsvec)
    }
    
    # Splicing positions
    if (!is.null(refcds[[j]]$intervals_splice)) {
      refcds[[j]]$dcvec_spl = as.integer(rle_cov[[refcds[[j]]$chr]][refcds[[j]]$intervals_splice])
    }
    
    if (round(j/2000)==(j/2000)) { message(sprintf('    %0.3g%% ...', round(j/length(refcds),2)*100)) } # Progress information
  }
  
  return(refcds)
  
} # EOF

    
  